# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_cart_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
