# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20181106_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='number',
            field=models.IntegerField(default=''),
        ),
    ]
