# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-07 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_cart_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
