# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-07 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20181107_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='number',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
