# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-07 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20181107_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='isselect',
            field=models.BooleanField(default=False),
        ),
    ]
